# ComfyUI extra_model_paths.yaml for darwin
comfyui_desktop:
  is_default: "true"
  checkpoints: /Volumes/MySSD/ComfyUI/models/checkpoints/
  clip: /Volumes/MySSD/ComfyUI/models/clip/
  clip_vision: /Volumes/MySSD/ComfyUI/models/clip_vision/
  configs: /Volumes/MySSD/ComfyUI/models/configs/
  controlnet: /Volumes/MySSD/ComfyUI/models/controlnet/
  diffusers: /Volumes/MySSD/ComfyUI/models/diffusers/
  diffusion_models: /Volumes/MySSD/ComfyUI/models/diffusion_models/
  embeddings: /Volumes/MySSD/ComfyUI/models/embeddings/
  gligen: /Volumes/MySSD/ComfyUI/models/gligen/
  hypernetworks: /Volumes/MySSD/ComfyUI/models/hypernetworks/
  ipadapters: /Volumes/MySSD/ComfyUI/models/ipadapters/
  loras: /Volumes/MySSD/ComfyUI/models/loras/
  style_models: /Volumes/MySSD/ComfyUI/models/style_models/
  unet: /Volumes/MySSD/ComfyUI/models/unet/
  upscale_models: /Volumes/MySSD/ComfyUI/models/upscale_models/
  vae: /Volumes/MySSD/ComfyUI/models/vae/
  vae_approx: /Volumes/MySSD/ComfyUI/models/vae_approx/
